providers = ["python", "node"]

[phases.build]
cmds = ['cd frontend && npm install', 'cd frontend && npm run build']

[start]
cmd = 'cd backend && flask db upgrade && gunicorn app:app --bind 0.0.0.0:$PORT --workers 2'
